version: "3.9"

services:
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    restart: unless-stopped
    ports:
      - "8081:80"

  graphql:
    build: ./graphql-server
    container_name: eval-graphql
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173,http://localhost:4173
    ports:
      - "4000:4000"
